version: "3"

services:

  net:
    image: k8s.gcr.io/pause
    ports:
    - 3003:3003

  db:
    image: mongo
    network_mode: service:net
    volumes:
    - ./mongodb-data:/data/db

  seed:
    build:
      context: redi-connect-backend
      target: dev
    network_mode: service:net
    volumes:
    - ./mongodb-data:/mongodb-data
    entrypoint:
    - sh
    - -c
    - |
      if [ -f /mongodb-data/seed-has-been-loaded ]; then
        echo "Seed data has already been loaded. If you want to reload it,"
        echo "rm mongodb-data/seed-has-been-loaded and try again."
      else
        ./seed-random-data.sh
        touch /mongodb-data/seed-has-been-loaded
      fi

  admin:
    build:
      context: redi-connect-admin
      target: dev
    tty: true
    volumes:
    - ./redi-connect-admin/:/src/
    ports:
    - 3002:3000

  backend:
    build:
      context: redi-connect-backend
      target: dev
    volumes:
    - ./redi-connect-backend/:/src/
    network_mode: service:net

  front:
    build:
      context: redi-connect-front
      target: dev
    tty: true
    environment:
      REDI_LOCATION: berlin
    volumes:
    - ./redi-connect-front/:/src/
    ports:
    - 3001:3000