name: Deploy backend webapp

on:
  push:
    branches:
      - develop
    paths:
      - 'redi-connect-backend/**'

env:
  AZURE_APP_SERVICE_NAME: app-staging-redi
  AZURE_CONTAINER_REGISTRY: registrystagingredi.azurecr.io
  AZURE_IMAGE_NAME_WITH_TAG: registrystagingredi.azurecr.io/rediconnect-backend:${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure container registry authentication
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build redi-connect-backend -t ${{ env.AZURE_IMAGE_NAME_WITH_TAG }}
          docker push ${{ env.AZURE_IMAGE_NAME_WITH_TAG }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_SERVICE_NAME }}
          images: ${{ env.AZURE_IMAGE_NAME_WITH_TAG }}

      - name: Azure logout
        run: |
          az logout