name: Mirorr to private repo

on: [push, delete]

jobs:
  to_mirror_repo:
    runs-on: ubuntu-latest
    steps: # <-- must use actions/checkout before mirroring!
      - name: repo-sync
        uses: wei/git-sync@v3
        with:
          source_repo: 'talent-connect/connect'
          destination_repo: 'talent-connect/connnect-ffg-private'
          source_branch: 'refs/remotes/source/*'
          destination_branch: 'refs/heads/*'
          destination_ssh_private_key: ${{ secrets.SYNC_REPOSITORY_DEPLOY_TOKEN }}
